language: python
python:
  - "3.6"
install:
  - "pip install mkdocs"
  - "pip install mkdocs-material"
script:
  - "mkdocs build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master