site_name: 'RedG User Documentation'
theme: 'material'
theme_dir: 'theme'
extra_css: ['css/style.css']
repo_name: 'btc-ag/redg'
repo_url: 'https://github.com/btc-ag/redg'
copyright: '© 2016-2018 <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">BTC Business Technology Consulting AG</span>&emsp;&emsp;<a href="https://btc-ag.github.io/imprint.html">Impressum / Imprint</a>&emsp;<a href="https://btc-ag.github.io/privacy.html">Datenschutzerklärung / Privacy Policy</a><br/> Unless stated otherwise, the <span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Text" property="dct:title" rel="dct:type">RedG User Documentation</span> is made available under CC-BY-SA 4.0 <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons Lizenzvertrag" style="vertical-align:text-bottom" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a>'
pages:
 - index.md
 - getting_started.md
 - specifying_test_data.md
 - 'Features':
     - 'Dummy data': 'features/dummy_data.md'
     - 'Visualization': 'features/visualization.md'
     - 'Data extraction': 'features/data_extractor.md'
     - 'JPA meta-model analysis': 'features/jpa_metamodel.md'
 - 'Integration':
     - 'Overview': 'integration/index.md'
     - 'Code generator':
        - 'Maven plugin': 'integration/maven_plugin.md'
        - 'Code generator API': 'integration/generator_api.md'
     - 'Runtime':
        - 'Runtime API': 'integration/runtime_api.md'
 - 'Customization':
     - 'Code generator':
         - 'Type mapping': 'customization/generator/type_mapping.md'
         - 'Name mapping': 'customization/generator/name_mapping.md'
         - 'Explicit attributes & foreign keys': 'customization/generator/explicit_attributes.md'
         - 'Convenience setter methods': 'customization/generator/convenience_setters.md'
     - 'Runtime':
         - 'Default value strategy': 'customization/runtime/default_value_strategy.md'
         - 'SQL values formatter': 'customization/runtime/sql_values_formatter.md'
         - 'PreparedStatement parameter setter': 'customization/runtime/prepared_statement_parameter_setter.md'
         - 'Dummy factory': 'customization/runtime/dummy_factory.md'
 - 'Development':
     - 'Quick Start Guide': 'development/quick_start_guide.md'
     - 'Debugging Maven plugin': 'development/debugging_plugin.md'
 - compatibility.md
 - 'License': 'about/license.md'
extra:
  logo: 'img/logo_white.svg'
  palette:
    primary: 'red'
    accent: 'indigo'
  social:
    - type: 'globe'
      link: 'https://www.btc-ag.com'
    - type: 'github'
      link: 'https://github.com/btc-ag/redg'

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - meta
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist(custom_checkbox=true)